force-app/main/default/objects/Litmos_Sync_Logs__c/Litmos_Sync_Logs__c.object-meta.xml
<CustomObject>
    <description>Holds records of syncs with Litmos to report success and failure on user creation and/or updates</description>
    <label>Litmos Sync Log</label>
    <nameField>
        <displayFormat>SYNC-{00000}</displayFormat>
        <label>Sync Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litmos Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Course involved in sync operation</description>
    <label>Course</label>
    <referenceTo>Litmos__Program__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Date_Time_of_Sync__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_of_Sync__c</fullName>
    <description>Date and time of sync initialization</description>
    <label>Date/Time of Sync</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Learning_Path__c.field-meta.xml
<CustomField>
    <fullName>Learning_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learning Path</label>
    <referenceTo>Litmos__LearningPath__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Litmos_Team__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Litmos Team</label>
    <referenceTo>Litmos_Team__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Litmos_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Litmos Team Member</label>
    <referenceTo>Litmos_Team_Member__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Litmos_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Litmos_User_Id__c</fullName>
    <description>Holds litmos user Id for quick reference</description>
    <label>Litmos User Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Module involved in sync operation</description>
    <label>Module</label>
    <referenceTo>Litmos__ModuleNew__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Status_of_Sync__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Sync__c</fullName>
    <description>Record the status of each sync</description>
    <label>Status of Sync</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Create</fullName>
            </value>
            <value>
                <fullName>Course Sync</fullName>
            </value>
            <value>
                <fullName>Learning Path Sync</fullName>
            </value>
            <value>
                <fullName>Module Sync</fullName>
            </value>
            <value>
                <fullName>Team</fullName>
            </value>
            <value>
                <fullName>Team Member</fullName>
            </value>
            <value>
                <fullName>Bulk Team Member</fullName>
            </value>
            <value>
                <fullName>Learning Path Program</fullName>
            </value>
            <value>
                <fullName>Course Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User being updated/created in Litmos</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Litmos_User_Syncs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/litmosSyncControllerTEST.cls
@isTest
public class litmosSyncControllerTEST {
	@testSetup
    static void setupData() {
        //insert user
        Profile standardUser = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User u1 = new User(
            FirstName = 'Test Sync Controller',
            LastName = 'Test Last',
            Litmos__OriginalId__c = 13488946,
            Litmos__LitmosUserId__c = 'ABCDE',
            Litmos__Litmos_Activated__c = true,
            ProfileId = standardUser.Id,
            isActive = true,
            email='team1@adminuser.com',
            Username='team1@adminuser.com',
            alias='team1',
            TimeZoneSidKey='America/New_York',
            LocaleSidKey='en_US',
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US'
        );
        insert u1;
        Litmos_Team__c team = new Litmos_Team__c(
        	Name = 'Test Team',
            Litmos_Id__c = 'TEAMTEST'
        );
        insert team;
        Litmos_Team_Member__c member = new Litmos_Team_Member__c(
        	Litmos_Team__c = team.Id,
            Learner__c = u1.Id,
            Litmos_User_Id__c = u1.Litmos__LitmosUserId__c
        );
        insert member;
        insert new Litmos__ModuleNew__c(Name = 'Test module');
        insert new Litmos__Program__c(Name = 'Test Course');
        insert new Litmos__LearningPath__c(Name='Test Learning Path');
        //user sync
        insert new Litmos_Sync_Logs__c(Type__c ='User Create',Status_of_Sync__c ='Success',User__c = u1.Id,Date_Time_of_Sync__c = Date.today());
        //module sync
        insert new Litmos_Sync_Logs__c(Type__c='Module Sync',Status_of_Sync__c ='Success',Module__c = [SELECT Id FROM Litmos__ModuleNew__c LIMIT 1].Id,Date_Time_of_Sync__c = Date.today());
        //path sync
        insert new Litmos_Sync_Logs__c(Type__c ='Learning Path Sync', Status_of_Sync__C = 'Success',Learning_Path__c = [SELECT Id FROM Litmos__LearningPath__c LIMIT 1].Id,Date_Time_of_Sync__c = Date.today());
        //program sync
        insert new Litmos_Sync_Logs__c(Type__c = 'Course Sync', Status_of_Sync__c = 'Success', Course__c = [SELECT Id FROM Litmos__Program__c LIMIT 1].Id,Date_Time_of_Sync__c = Date.today());
    }
    @isTest
    static void runTests() {
        System.assertEquals(1, litmosSyncController.getUserSyncInfo().size());
        System.assertEquals(1, litmosSyncController.getModuleSync().size());
        System.assertEquals(1, litmosSyncController.getLearningPathSync().size());
        System.assertEquals(1, litmosSyncController.getProgramSync().size());
    }
}