force-app/main/default/objects/Litmos_Sync_Logs__c/Litmos_Sync_Logs__c.object-meta.xml
<CustomObject>
    <description>Holds records of syncs with Litmos to report success and failure on user creation and/or updates</description>
    <label>Litmos Sync Log</label>
    <nameField>
        <displayFormat>SYNC-{00000}</displayFormat>
        <label>Sync Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litmos Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Course involved in sync operation</description>
    <label>Course</label>
    <referenceTo>Litmos__Program__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Date_Time_of_Sync__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_of_Sync__c</fullName>
    <description>Date and time of sync initialization</description>
    <label>Date/Time of Sync</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Learning_Path__c.field-meta.xml
<CustomField>
    <fullName>Learning_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learning Path</label>
    <referenceTo>Litmos__LearningPath__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Litmos_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Litmos_User_Id__c</fullName>
    <description>Holds litmos user Id for quick reference</description>
    <label>Litmos User Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Module involved in sync operation</description>
    <label>Module</label>
    <referenceTo>Litmos__ModuleNew__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Status_of_Sync__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Sync__c</fullName>
    <description>Record the status of each sync</description>
    <label>Status of Sync</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Sync_Issues__c.field-meta.xml
<CustomField>
    <fullName>Sync_Issues__c</fullName>
    <description>Description of sync errors. Can be issue with trigger or server error.</description>
    <label>Sync Issues</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Create</fullName>
            </value>
            <value>
                <fullName>Course Sync</fullName>
            </value>
            <value>
                <fullName>Learning Path Sync</fullName>
            </value>
            <value>
                <fullName>Module Sync</fullName>
            </value>
            <value>
                <fullName>Team</fullName>
            </value>
            <value>
                <fullName>Team Member</fullName>
            </value>
            <value>
                <fullName>Bulk Team Member</fullName>
            </value>
            <value>
                <fullName>Learning Path Program</fullName>
            </value>
            <value>
                <fullName>Course Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User being updated/created in Litmos</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Litmos_User_Syncs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/litmosSyncController.cls
public class litmosSyncController {
	@AuraEnabled(cacheable=true)
    public static List<Litmos_Sync_Logs__c> getUserSyncInfo() {
        System.debug([SELECT Id,Name,User__r.Name,Date_Time_of_Sync__c,Litmos_User_Id__c,Status_of_Sync__c,Sync_Issues__c FROM Litmos_Sync_Logs__c WHERE Type__c = 'User Create']);
        return [SELECT Id,Name,User__r.Name,Date_Time_of_Sync__c,User__r.Litmos__LitmosUserId__c,Status_of_Sync__c,Sync_Issues__c FROM Litmos_Sync_Logs__c WHERE Type__c = 'User Create' ORDER BY Date_Time_of_Sync__c];
    }
    @AuraEnabled(cacheable=true)
    public static List<Litmos_Sync_Logs__c> getModuleSync() {
        return [SELECT Id,Name,Date_Time_of_Sync__c,Status_of_Sync__c,Sync_Issues__c,Module__r.Name FROM Litmos_Sync_Logs__c WHERE Type__c = 'Module Sync' ORDER BY Date_Time_of_Sync__c];
    }
    @AuraEnabled(cacheable=true)
    public static List<Litmos_Sync_Logs__c> getProgramSync() {
        return [SELECT Id,Name,Date_Time_of_Sync__c,Status_of_Sync__c,Sync_Issues__c,Course__r.Name FROM Litmos_Sync_Logs__c WHERE Type__c = 'Course Sync' ORDER BY Date_Time_of_Sync__c];
    }
    @AuraEnabled(cacheable=true) 
    public static List<Litmos_Sync_Logs__c> getLearningPathSync() {
        return [SELECT Id,Name,Date_Time_of_Sync__c,Status_of_Sync__c,Sync_Issues__c,Learning_Path__r.Name FROM Litmos_Sync_Logs__c WHERE Type__c = 'Learning Path Sync' ORDER BY Date_Time_of_Sync__c];
    }

}