force-app/main/default/objects/Litmos_Sync_Logs__c/Litmos_Sync_Logs__c.object-meta.xml
<CustomObject>
    <description>Holds records of syncs with Litmos to report success and failure on user creation and/or updates</description>
    <label>Litmos Sync Log</label>
    <nameField>
        <displayFormat>SYNC-{00000}</displayFormat>
        <label>Sync Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litmos Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Course involved in sync operation</description>
    <label>Course</label>
    <referenceTo>Litmos__Program__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Date_Time_of_Sync__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_of_Sync__c</fullName>
    <description>Date and time of sync initialization</description>
    <label>Date/Time of Sync</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Learning_Path__c.field-meta.xml
<CustomField>
    <fullName>Learning_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learning Path</label>
    <referenceTo>Litmos__LearningPath__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Litmos_Team__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Litmos Team</label>
    <referenceTo>Litmos_Team__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Litmos_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Litmos_Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Litmos Team Member</label>
    <referenceTo>Litmos_Team_Member__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Module involved in sync operation</description>
    <label>Module</label>
    <referenceTo>Litmos__ModuleNew__c</referenceTo>
    <relationshipLabel>Litmos Sync Logs</relationshipLabel>
    <relationshipName>Litmos_Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Status_of_Sync__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Sync__c</fullName>
    <description>Record the status of each sync</description>
    <label>Status of Sync</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Sync_Information__c.field-meta.xml
<CustomField>
    <fullName>Sync_Information__c</fullName>
    <description>Field to hold information about sync, such as number of team members uploaded when in bulk. Not for describing issues.</description>
    <label>Sync Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Sync_Issues__c.field-meta.xml
<CustomField>
    <fullName>Sync_Issues__c</fullName>
    <description>Description of sync errors. Can be issue with trigger or server error.</description>
    <label>Sync Issues</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Create</fullName>
            </value>
            <value>
                <fullName>Course Sync</fullName>
            </value>
            <value>
                <fullName>Learning Path Sync</fullName>
            </value>
            <value>
                <fullName>Module Sync</fullName>
            </value>
            <value>
                <fullName>Team</fullName>
            </value>
            <value>
                <fullName>Team Member</fullName>
            </value>
            <value>
                <fullName>Bulk Team Member</fullName>
            </value>
            <value>
                <fullName>Learning Path Program</fullName>
            </value>
            <value>
                <fullName>Course Module</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Litmos_Sync_Logs__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User being updated/created in Litmos</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Litmos_User_Syncs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/litmosSyncLogs.cls
public class litmosSyncLogs {
	//record sync logs
	//successful sync
    public static void logUserSuccess(List<User> users) {
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(User u : users) {
            logs.add(new Litmos_Sync_Logs__c(User__c = u.Id,Type__c = 'User Create', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c ='Success'));
        }
        insert logs;
    }
    //sync failure
    //potentially send email or alert of some kind
    public static void logUserErrors(List<User> users, Map<String,String> errors) {
        List<Litmos_Sync_Logs__c> errorLogs = new List<Litmos_Sync_Logs__c>();
        for(User u : users) {
            errorLogs.add(new Litmos_Sync_Logs__c(User__c = u.Id, Type__c = 'User Create', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c = 'Error',Sync_Issues__c = errors.get(u.Id)));
        }
		insert errorLogs;
    }
   public static void logModuleSuccess(List<Litmos__ModuleNew__c> modules) {
       List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
       for(Litmos__ModuleNew__c module : modules) {
            logs.add(new Litmos_Sync_Logs__c(Module__c = module.Id,Type__c = 'Module Sync', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c ='Success'));
       }
       insert logs;
   }
   public static void logModuleErrors(List<Litmos__ModuleNew__c> modules, Map<String,String> errors) {
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(Litmos__ModuleNew__c module : modules) {
                logs.add(new Litmos_Sync_Logs__c(Module__c = module.Id,Type__c = 'Module Sync', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c ='Error',Sync_Issues__c = errors.get(module.Id)));
        }
        insert logs;   
   }

   public static void logCourseSuccess(Set<Id> programs) {
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(Id program : programs) {
            logs.add(new Litmos_Sync_Logs__c(Course__c = program,Type__c = 'Course Sync', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c ='Success'));
        }
        insert logs;
   }
   public static void logCourseErrors(Set<Id> programs, Map<Id,String> errors) {
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(Id program : programs) {
            logs.add(new Litmos_Sync_Logs__c(Course__c = program,Type__c = 'Course Sync', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c ='Error',Sync_Issues__c = errors.get(program)));
        }
        insert logs;
   }

   public static void logPathSucccess(Set<Id> paths) {
    List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
    for(Id path : paths) {
        logs.add(new Litmos_Sync_Logs__c(Learning_Path__c = path,Type__c = 'Learning Path Sync', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c ='Success'));
    }
    insert logs;
}
public static void logPathErrors(Set<Id> paths, Map<Id,String> errors) {
    List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
    for(Id path : paths) {
        logs.add(new Litmos_Sync_Logs__c(Learning_Path__c = path,Type__c = 'Learning Path Sync', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c ='Error', Sync_Issues__c = errors.get(path)));
    }
        insert logs;
   }
    public static void logPathCourseSuccess(List<Litmos__LearningPathProgram__c> pathPrograms) {
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(Litmos__LearningPathProgram__c pathProg : pathPrograms) {
            logs.add(new Litmos_Sync_Logs__c(Learning_Path__c = pathProg.Litmos__LearningPathId__c,Course__c = pathProg.Litmos__ProgramID__c, Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c ='Success',Type__c='Learning Path Program'));
        }
        insert logs;
    }
    public static void logPathCourseError(List<String> errors) {
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(String e : errors) {
            logs.add(new Litmos_Sync_Logs__c(Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c='Error',Type__c='Learning Path Program',Sync_Issues__c = e));
        }
		insert logs;
    }
    public static void logTeamsSuccess(List<Litmos_Team__c> teams) {
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(Litmos_Team__c team : teams) {
            logs.add(new Litmos_Sync_Logs__c(Litmos_Team__c = team.Id, Type__c = 'Team', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c = 'Success'));
        }
        insert logs;
    }
    public static void logTeamsErrors(List<Litmos_Team__c> teams, Map<String,String> errors) {
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(Litmos_Team__c team : teams) {
            logs.add(new Litmos_Sync_Logs__c(Litmos_Team__c = team.Id, Type__c = 'Team', Date_Time_of_Sync__c = Date.today(), Status_of_Sync__c = 'Error', Sync_Issues__c = errors.get(team.Id)));
        }
        insert logs;
    }
    public static void logTeamMemberSuccess(List<Litmos_Team_Member__c> members) {
        System.debug('inside success log');
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        if(members.size() > 50) {
            logs.add(new Litmos_Sync_Logs__c(Type__c = 'Bulk Team Member', Date_Time_of_Sync__c = DateTime.now(), Status_of_Sync__c = 'Success',Sync_Information__c=members.size() + ' team members inserted'));
        } else {
            for(Litmos_Team_Member__c member : members) {
            logs.add(new Litmos_Sync_Logs__c(Litmos_Team_Member__c = member.Id, Type__c = 'Team Member', Date_Time_of_Sync__c = Datetime.now(), Status_of_Sync__c = 'Success'));
        	}
        }
        insert logs;
    }
    public static void logTeamMemberErrors(List<String> errors) {
        //no known team or member; generic error
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(String e : errors) {
            System.debug('sync error: ' + e);
            logs.add(new Litmos_Sync_Logs__c(Type__c = 'Team Member',Date_Time_of_Sync__c = Datetime.now(), Status_of_Sync__c = 'Error', Sync_Issues__c = e));
        }
        insert logs;
    }
    public static void logTeamMemberErrors(Map<String,String> errors) {
        //errors:
            // keySet: Litmos_Team__c Ids
            // values: error message
        List<Litmos_Sync_Logs__c> logs = new List<Litmos_Sync_Logs__c>();
        for(String team : errors.keySet()) {
            logs.add(new Litmos_Sync_Logs__c(
            	Type__c='Team Member',
                Date_Time_of_Sync__c = Datetime.now(),
                Status_of_Sync__c = 'Error',
                Sync_Issues__c = errors.get(team),
                Litmos_Team__c = team
            ));
        }
        insert logs;
        
    }
    public static void logTeamMemberDeletions(Integer numDeletions, Id teamId) {
        Litmos_Sync_Logs__c log = new Litmos_Sync_Logs__c(
        	Litmos_Team__c = teamId,
            Type__c = 'Team Member',
            Date_Time_of_Sync__c = Datetime.now(),
            Status_of_Sync__c = 'Success',
            Sync_Information__c = numDeletions + ' team members deleted from team: ' + [SELECT Name From Litmos_Team__c WHERE Id = :teamId].Name
        );
        insert log;
    }
}